version: '2.2'
services:
  eureka-service:
    container_name: eureka-service
    build:
      context: .
      dockerfile: Dockerfile-eurekaservice
    image: eureka-service:latest
    expose:
      - 8761
    ports:
      - 8761:8761
    environment:
      - EUREKA_CLIENT_REGISTER_WITH_EUREKA=false
      - EUREKA_CLIENT_FETCH_REGISTRY=false
    networks:
      - cinema-app-network
  mysql-user-service:
    image: mysql:5.7.22
    container_name: mysql-user-service
    ports:
      - 3306:3306
    networks:
      - cinema-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=user_service_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  mysql-cinema-service:
    image: mysql:5.7.22
    container_name: mysql-cinema-service
    ports:
    - 3307:3306
    networks: 
      - cinema-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=cinema_service_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  mysql-movie-service:
    image: mysql:5.7.22
    container_name: mysql-movie-service
    ports:
    - 3308:3306
    networks: 
      - cinema-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=movie_service_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  mysql-payment-service:
    image: mysql:5.7.22
    container_name: mysql-payment-service
    ports:
    - 3309:3306
    networks: 
      - cinema-app-network
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=payment_service_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=user
  rabbitmq-server:
    image: rabbitmq:3.7.4
    hostname: rabbitmq-server
    container_name: rabbitmq-server
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - cinema-app-network
  user-service:
    container_name: user-service
    build:
      context: .
      dockerfile: Dockerfile-userservice
    image: user-service:latest
    expose:
      - 8090
    ports:
      - 8090:8090
    networks:
      - cinema-app-network
    links:
      - "eureka-service"
    depends_on:
      - eureka-service
      - mysql-user-service
      - rabbitmq-server
    environment:
      - DATABASE_HOST=mysql-user-service
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=user_service_db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-user-service:3306/user_service_db
      - SPRING_APPLICATION_NAME=user-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq-server
  cinema-service:
    container_name: cinema-service
    build:
      context: .
      dockerfile: Dockerfile-cinemaservice
    image: cinema-service:latest
    expose:
      - 9090
    ports:
      - 9090:9090
    networks:
      - cinema-app-network
    links:
      - "eureka-service"
    depends_on:
      - eureka-service
      - mysql-cinema-service
      - rabbitmq-server
    environment:
      - DATABASE_HOST=mysql-cinema-service
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=cinema_service_db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-cinema-service:3306/cinema_service_db
      - SPRING_APPLICATION_NAME=cinema-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq-server
  movie-service:
    container_name: movie-service
    build:
      context: .
      dockerfile: Dockerfile-movieservice
    image: movie-service:latest
    expose:
      - 9091
    ports:
      - 9091:9091
    networks:
      - cinema-app-network
    links:
      - "eureka-service"
    depends_on:
      - eureka-service
      - mysql-movie-service
      - rabbitmq-server
    environment:
      - DATABASE_HOST=mysql-movie-service
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=movie_service_db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-movie-service:3306/movie_service_db
      - SPRING_APPLICATION_NAME=movie-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq-server
      - TMDB_APIKEY=5b5a9f89ddd9f24679aa33e73cdd0a7a
  payment-service:
    container_name: payment-service
    build:
      context: .
      dockerfile: Dockerfile-paymentservice
    image: payment-service:latest
    expose:
      - 9092
    ports:
      - 9092:9092
    networks:
      - cinema-app-network
    links:
      - "eureka-service"
    depends_on:
      - eureka-service
      - mysql-payment-service
      - rabbitmq-server
    environment:
      - DATABASE_HOST=mysql-payment-service
      - DATABASE_USER=user
      - DATABASE_PASSWORD=user
      - DATABASE_NAME=payment_service_db
      - DATABASE_PORT=3306
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-payment-service:3306/payment_service_db
      - SPRING_APPLICATION_NAME=payment-service
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka
      - SPRING_RABBITMQ_HOST=rabbitmq-server
  gatway:
    container_name: gateway
    build:
      context: .
      dockerfile: Dockerfile-gateway
    image: gateway-service:latest
    expose:
      - 9093
    ports:
      - 9093:9093
    networks:
      - cinema-app-network
    links:
      - "eureka-service"
    depends_on:
      - eureka-service
    environment:
      - SPRING_APPLICATION_NAME=gateway
      - SPRING_PROFILES_ACTIVE=enableEureka
      - EUREKA_INSTANCE_PREFER_IP_ADDRESS=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-service:8761/eureka

    logging:
      driver: json-file
networks: 
  cinema-app-network:
    driver: bridge
